export const KEYWORDS = {
  cak: "let",
  cok: "const",
  bener: "true",
  salah: "false",
  "gak-ono": "null",
  "gak-ditetepake": "undefined",
  lek: "if",
  berarti: "else",
  "lek-gak-ngono": "else if",
  milih: "switch",
  nek: "case",
  leren: "break",
  balekno: "return",
  muter: "for",
  saklawase: "while",
  terus: "continue",
  saben: "for_of",
  teko: "from",
  nganti: "to",
  gawe: "function",
  kelas: "class",
  anyar: "new",
  iki: "this",
  turunan: "extends",
  janji: "async",
  enteni: "await",
  coba: "try",
  "nek-eror": "catch",
  pasti: "finally",
  uncal: "throw",
  gowo: "import",
  kirim: "export",
  tulis: "console.log",
  takon: "readline",
  lan: "&&",
  utowo: "||",
  gak: "!",
  podho: "===",
  "gak-podho": "!=="
};

export const MULTI_WORD_KEYWORDS = [
  "lek-gak-ngono",
  "berarti",
  "nek-eror",
  "gak-ditetepake",
  "gak-podho"
];
